### ISSUE TITLE
발표 가이드

### ISSUE THREAD

**Issue by randomfog42** [fedgkr/feconf-notice#3]
> FEConf의 모든 발표자는 FEConf [Code of Conduct](https://github.com/fedgkr/feconf-notice/issues/2)를 준수해야 합니다.
> 발표 및 발표 자료를 만들때 다음을 참고해 주세요.

## 절대 해서는 안될 것

* [Code of Conduct](https://github.com/fedgkr/feconf-notice/issues/2)에 위배되는 사항을 포함하지 마세요.
* 특히 발표 성차별적인 자료, 혐오/폭력적인 자료는 절대 허용하지 않습니다.
  애매하다면 오거나이저에게 검증을 요청해 주세요.

## 청중이 좋아하는 발표는 어떤 발표인가요?

* 오랜 기간 고민을 통해 해결한 가치 있는 경험과 사례를 좋아합니다.
* 청중의 수준에 맞게 발표할 내용을 쉽고 자세하게 도표나 그림 등을 활용해 전달합니다.
* 많은 내용보다는 중요하다고 생각하는 몇 개에 초점을 맞춥니다.

## 청중의 만족도가 낮은 발표는 어떤 발표인가요??

* 기술에 대한 인사이트 없이 회사 홍보나 성과를 자랑하는 발표입니다.
* 코드만 있어서 발표 자료를 읽기 힘들 때, 너무 많은 페이지가 빠르게 넘어가는 발표를 특히 싫어합니다.
* 청중은 정해진 시간을 넘기는 발표를 피곤해 합니다.

## 발표자료 작성 팁

* 행사 전 미리 발표 자료를 참가자에게 공유하기 위해 공개 버전의 PDF 또는 열람할 수 있는 온라인 URL을 알려주세요.
* 화면 하단 15%는 사용하지 않습니다. 영상에서 발표내용 전달이 어려울 수 있습니다.
* 폰트는 생각보다 더 크게 해 주세요. 본문은 최소 22포인트 이상 권장합니다.
* 배경은 흰색으로 하는 것이 가독성이 좋습니다.
* 저작권 이슈가 있는 리소스는 사용하지 않거나 출처를 꼭 명시해 주세요.

### 코드를 보여줘야 할 경우
* 코드는 단순한 색깔로 하이라이팅 하고 폰트 크기를 조금 더 크게 해 주세요.
* 코드에 많은 색깔(특히 빨강)이 사용된다면 반드시 흰색 배경을 사용하세요.
* 코드는 핵심부분만 추려서 하이라이팅을 해 주세요. https://carbon.now.sh/ 사용하면 좋습니다.
* 라이브 코딩은 준비해야 할 것이 많습니다. 폰트크기, 배경, 확실한 시나리오 등등
  * 평소 코딩하던 설정으로는 발표에 적합하지 않아요.
  * 코딩 내용을 영상으로 찍어 플레이 하는 것도 좋은 방법입니다.

## 발표 후 질의 응답

* 따로 질의 응답 시간은 없습니다.
* 발표 영상이 공개되는 시간에 온라인으로 함께 해주시면 감사하겠습니다.

## 참고 자료

* 이전에 진행된 동영상을 통해 다른 분들의 발표 내용을 참고하실 수 있습니다.
  * https://www.youtube.com/channel/UCWEzfYIpFBIG5jh6laXC6hA

**Comment by jbee37142** [comment]
https://www.notion.so/fef5df0f495a4e05a9da95793040999f
